server:
  port: 8200
  servlet:
    context-path: /webcore
  compression:
    #响应的资源压缩，压缩后未为原来的1/3
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webcore?characterEncoding=utf8&useSSL=false&&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/,file:static/
    excludeUrls: /demo/**
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  #json 时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#mybatis plus 设置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  mapper-locations: classpath*:com/bzchao/**/xml/*Mapper.xml
  # 枚举配置。支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.bzchao
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型
      id-type: AUTO
      # 默认数据库表下划线命名
      table-underline: true

#是否激活swagger true or false
swagger:
  enable: true
